# Generated by Django 4.2.29 on 2026-03-31 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mesas", "0001_initial"),
        ("catalogo", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Comanda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado en"),
                ),
                (
                    "numero",
                    models.PositiveIntegerField(
                        help_text="Se genera automáticamente al abrir.",
                        unique=True,
                        verbose_name="Número de comanda",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("abierta", "Abierta"),
                            ("enviada", "Enviada a cocina"),
                            ("lista", "Lista para cobrar"),
                            ("cerrada", "Cerrada / Cobrada"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="abierta",
                        max_length=12,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "cantidad_personas",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Cantidad de personas"
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, verbose_name="Observaciones generales"
                    ),
                ),
                (
                    "cerrada_en",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Cerrada en"
                    ),
                ),
                (
                    "mesa",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null si es para llevar o delivery.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="comandas",
                        to="mesas.mesa",
                        verbose_name="Mesa",
                    ),
                ),
                (
                    "mozo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="comandas_asignadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Mozo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comanda",
                "verbose_name_plural": "Comandas",
                "ordering": ["-creado_en"],
            },
        ),
        migrations.CreateModel(
            name="ItemComanda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado en"),
                ),
                (
                    "cantidad",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Cantidad"
                    ),
                ),
                (
                    "precio_unitario",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Precio unitario"
                    ),
                ),
                (
                    "observaciones",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Observaciones del ítem",
                    ),
                ),
                (
                    "estado_cocina",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("en_preparacion", "En preparación"),
                            ("listo", "Listo"),
                            ("entregado", "Entregado"),
                        ],
                        default="pendiente",
                        max_length=15,
                        verbose_name="Estado en cocina",
                    ),
                ),
                (
                    "enviado_cocina",
                    models.BooleanField(
                        default=False,
                        help_text="True desde el momento en que se envió a la pantalla de cocina.",
                        verbose_name="Enviado a cocina",
                    ),
                ),
                (
                    "cancelado",
                    models.BooleanField(default=False, verbose_name="Cancelado"),
                ),
                (
                    "cancelado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items_cancelados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cancelado por",
                    ),
                ),
                (
                    "comanda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="comandas.comanda",
                        verbose_name="Comanda",
                    ),
                ),
                (
                    "combo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalogo.combo",
                        verbose_name="Combo",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items_comanda",
                        to="catalogo.producto",
                        verbose_name="Producto",
                    ),
                ),
                (
                    "variante",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalogo.varianteproducto",
                        verbose_name="Variante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ítem de comanda",
                "verbose_name_plural": "Ítems de comanda",
                "ordering": ["creado_en"],
            },
        ),
    ]
