# Generated by Django 4.2.29 on 2026-03-31 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=120, verbose_name="Nombre del negocio"),
                ),
                (
                    "razon_social",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Razón social"
                    ),
                ),
                (
                    "cuit",
                    models.CharField(blank=True, max_length=20, verbose_name="CUIT"),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Teléfono"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "direccion",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Dirección"
                    ),
                ),
                (
                    "ciudad",
                    models.CharField(blank=True, max_length=100, verbose_name="Ciudad"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="configuracion/logos/",
                        verbose_name="Logo",
                    ),
                ),
                (
                    "moneda",
                    models.CharField(
                        default="ARS", max_length=10, verbose_name="Moneda"
                    ),
                ),
                (
                    "zona_horaria",
                    models.CharField(
                        default="America/Argentina/Buenos_Aires",
                        max_length=60,
                        verbose_name="Zona horaria",
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Empresa",
                "verbose_name_plural": "Empresa",
            },
        ),
        migrations.CreateModel(
            name="HorarioNegocio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dia",
                    models.CharField(
                        choices=[
                            ("lunes", "Lunes"),
                            ("martes", "Martes"),
                            ("miercoles", "Miércoles"),
                            ("jueves", "Jueves"),
                            ("viernes", "Viernes"),
                            ("sabado", "Sábado"),
                            ("domingo", "Domingo"),
                        ],
                        max_length=10,
                        unique=True,
                        verbose_name="Día",
                    ),
                ),
                ("apertura", models.TimeField(verbose_name="Hora de apertura")),
                ("cierre", models.TimeField(verbose_name="Hora de cierre")),
                (
                    "cierre_siguiente_dia",
                    models.BooleanField(
                        default=False,
                        help_text="Marcar si el horario de cierre es pasada la medianoche.",
                        verbose_name="Cierra al día siguiente",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
            ],
            options={
                "verbose_name": "Horario del negocio",
                "verbose_name_plural": "Horarios del negocio",
                "ordering": ["dia"],
            },
        ),
    ]
