# Generated by Django 4.2.29 on 2026-04-02 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuracion", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="empresa",
            name="cuit",
        ),
        migrations.AddField(
            model_name="empresa",
            name="rut",
            field=models.CharField(blank=True, max_length=20, verbose_name="RUT"),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="moneda",
            field=models.CharField(default="UYU", max_length=10, verbose_name="Moneda"),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="zona_horaria",
            field=models.CharField(
                default="America/Montevideo", max_length=60, verbose_name="Zona horaria"
            ),
        ),
    ]
