# Generated by Django 4.2.29 on 2026-03-31 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado en"),
                ),
                ("nombre", models.CharField(max_length=80, verbose_name="Nombre")),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "imagen",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="catalogo/categorias/",
                        verbose_name="Imagen",
                    ),
                ),
                (
                    "orden",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Número menor aparece primero en el menú.",
                        verbose_name="Orden",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "visible_menu_qr",
                    models.BooleanField(
                        default=True, verbose_name="Visible en menú QR"
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoría",
                "verbose_name_plural": "Categorías",
                "ordering": ["orden", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="Combo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado en"),
                ),
                ("nombre", models.CharField(max_length=120, verbose_name="Nombre")),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "imagen",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="catalogo/combos/",
                        verbose_name="Imagen",
                    ),
                ),
                (
                    "precio",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Precio del combo"
                    ),
                ),
                (
                    "disponible",
                    models.BooleanField(default=True, verbose_name="Disponible"),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "visible_salon",
                    models.BooleanField(default=True, verbose_name="Visible en salón"),
                ),
                (
                    "visible_online",
                    models.BooleanField(
                        default=False, verbose_name="Visible en pedidos online"
                    ),
                ),
            ],
            options={
                "verbose_name": "Combo",
                "verbose_name_plural": "Combos",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Extra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado en"),
                ),
                ("nombre", models.CharField(max_length=80, verbose_name="Nombre")),
                (
                    "precio",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Precio adicional",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
            ],
            options={
                "verbose_name": "Extra",
                "verbose_name_plural": "Extras",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado en"),
                ),
                ("nombre", models.CharField(max_length=120, verbose_name="Nombre")),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "imagen",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="catalogo/productos/",
                        verbose_name="Imagen",
                    ),
                ),
                (
                    "precio_costo",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Precio de costo",
                    ),
                ),
                (
                    "precio_venta",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Precio de venta"
                    ),
                ),
                (
                    "disponible",
                    models.BooleanField(
                        default=True,
                        help_text="Fuera de disponibilidad temporaria (sin eliminar).",
                        verbose_name="Disponible",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "visible_salon",
                    models.BooleanField(default=True, verbose_name="Visible en salón"),
                ),
                (
                    "visible_menu_qr",
                    models.BooleanField(
                        default=True, verbose_name="Visible en menú QR"
                    ),
                ),
                (
                    "visible_online",
                    models.BooleanField(
                        default=False, verbose_name="Visible en pedidos online"
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="productos",
                        to="catalogo.categoria",
                        verbose_name="Categoría",
                    ),
                ),
                (
                    "extras",
                    models.ManyToManyField(
                        blank=True,
                        related_name="productos",
                        to="catalogo.extra",
                        verbose_name="Extras disponibles",
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto",
                "verbose_name_plural": "Productos",
                "ordering": ["categoria", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="HistorialPrecio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "precio_anterior",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Precio anterior"
                    ),
                ),
                (
                    "precio_nuevo",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Precio nuevo"
                    ),
                ),
                (
                    "fecha",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha"),
                ),
                (
                    "modificado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modificado por",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial_precios",
                        to="catalogo.producto",
                        verbose_name="Producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial de precio",
                "verbose_name_plural": "Historial de precios",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="VarianteProducto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado en"),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=80, verbose_name="Nombre de la variante"
                    ),
                ),
                (
                    "delta_precio",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Suma o resta al precio base del producto. Puede ser negativo.",
                        max_digits=10,
                        verbose_name="Diferencia de precio",
                    ),
                ),
                (
                    "disponible",
                    models.BooleanField(default=True, verbose_name="Disponible"),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variantes",
                        to="catalogo.producto",
                        verbose_name="Producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Variante de producto",
                "verbose_name_plural": "Variantes de producto",
                "unique_together": {("producto", "nombre")},
            },
        ),
        migrations.CreateModel(
            name="ItemCombo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantidad",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Cantidad"
                    ),
                ),
                (
                    "combo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="catalogo.combo",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="en_combos",
                        to="catalogo.producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ítem de combo",
                "verbose_name_plural": "Ítems de combo",
                "unique_together": {("combo", "producto")},
            },
        ),
    ]
