# Generated by Django 4.2.29 on 2026-04-01 01:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado en"),
                ),
                ("nombre", models.CharField(max_length=150, verbose_name="Nombre")),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "imagen",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="eventos/",
                        verbose_name="Imagen",
                    ),
                ),
                ("fecha", models.DateField(verbose_name="Fecha")),
                ("hora_inicio", models.TimeField(verbose_name="Hora de inicio")),
                (
                    "hora_fin",
                    models.TimeField(blank=True, null=True, verbose_name="Hora de fin"),
                ),
                (
                    "cupos_totales",
                    models.PositiveIntegerField(verbose_name="Cupos totales"),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "visible_publico",
                    models.BooleanField(default=True, verbose_name="Visible en web"),
                ),
            ],
            options={
                "verbose_name": "Evento",
                "verbose_name_plural": "Eventos",
                "ordering": ["-fecha", "-hora_inicio"],
            },
        ),
        migrations.CreateModel(
            name="TipoEntrada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=80, verbose_name="Nombre")),
                (
                    "descripcion",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Descripción"
                    ),
                ),
                (
                    "precio",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Precio"
                    ),
                ),
                ("cupos", models.PositiveIntegerField(verbose_name="Cupos")),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tipos_entrada",
                        to="eventos.evento",
                        verbose_name="Evento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de entrada",
                "verbose_name_plural": "Tipos de entrada",
                "ordering": ["precio"],
            },
        ),
        migrations.CreateModel(
            name="Entrada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado en"),
                ),
                (
                    "nombre_comprador",
                    models.CharField(
                        max_length=120, verbose_name="Nombre del comprador"
                    ),
                ),
                (
                    "email_comprador",
                    models.EmailField(
                        max_length=254, verbose_name="Email del comprador"
                    ),
                ),
                (
                    "telefono_comprador",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Teléfono"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente de pago"),
                            ("pagada", "Pagada"),
                            ("validada", "Validada en acceso"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="pendiente",
                        max_length=10,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "medio_pago",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("efectivo", "Efectivo"),
                            ("mercado_pago", "Mercado Pago"),
                            ("transferencia", "Transferencia"),
                        ],
                        max_length=15,
                        verbose_name="Medio de pago",
                    ),
                ),
                (
                    "precio_pagado",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Precio pagado",
                    ),
                ),
                (
                    "codigo_qr",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Código QR",
                    ),
                ),
                (
                    "validada_en",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Validada en"
                    ),
                ),
                (
                    "observaciones",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Observaciones"
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="entradas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cliente registrado",
                    ),
                ),
                (
                    "tipo_entrada",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entradas",
                        to="eventos.tipoentrada",
                        verbose_name="Tipo de entrada",
                    ),
                ),
                (
                    "validada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="entradas_validadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Validada por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entrada",
                "verbose_name_plural": "Entradas",
                "ordering": ["-creado_en"],
            },
        ),
    ]
