# Generated by Django 4.2.29 on 2026-03-31 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RegistroAuditoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modulo", models.CharField(max_length=50, verbose_name="Módulo")),
                (
                    "accion",
                    models.CharField(
                        choices=[
                            ("login", "Inicio de sesión"),
                            ("logout", "Cierre de sesión"),
                            ("crear", "Creación"),
                            ("editar", "Edición"),
                            ("eliminar", "Eliminación"),
                            ("desactivar_usuario", "Desactivar usuario"),
                            ("cambio_contrasena", "Cambio de contraseña"),
                            ("cobro", "Cobro"),
                            ("apertura_caja", "Apertura de caja"),
                            ("cierre_caja", "Cierre de caja"),
                            ("envio_cocina", "Envío a cocina"),
                            ("otro", "Otro"),
                        ],
                        default="otro",
                        max_length=30,
                        verbose_name="Acción",
                    ),
                ),
                ("detalle", models.TextField(blank=True, verbose_name="Detalle")),
                (
                    "ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP"
                    ),
                ),
                (
                    "fecha",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha y hora"
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de auditoría",
                "verbose_name_plural": "Registros de auditoría",
                "ordering": ["-fecha"],
            },
        ),
    ]
