# Generated by Django 4.2.29 on 2026-04-01 01:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Empleado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado en"),
                ),
                (
                    "documento",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="DNI / Documento"
                    ),
                ),
                (
                    "direccion",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Dirección"
                    ),
                ),
                (
                    "telefono_emergencia",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Teléfono de emergencia"
                    ),
                ),
                (
                    "contacto_emergencia",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Contacto de emergencia",
                    ),
                ),
                (
                    "fecha_nacimiento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de nacimiento"
                    ),
                ),
                (
                    "fecha_ingreso",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de ingreso"
                    ),
                ),
                (
                    "tipo_contrato",
                    models.CharField(
                        choices=[
                            ("hora", "Por hora"),
                            ("fijo", "Salario fijo"),
                            ("eventual", "Eventual"),
                        ],
                        default="hora",
                        max_length=10,
                        verbose_name="Tipo de contrato",
                    ),
                ),
                (
                    "costo",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Costo ($/hora o $/mes según tipo)",
                    ),
                ),
                ("notas", models.TextField(blank=True, verbose_name="Notas internas")),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil_empleado",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario del sistema",
                    ),
                ),
            ],
            options={
                "verbose_name": "Empleado",
                "verbose_name_plural": "Empleados",
                "ordering": ["usuario__last_name", "usuario__first_name"],
            },
        ),
    ]
