# Generated by Django 4.2.29 on 2026-04-01 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pedidos", "0001_initial"),
        ("comandas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Comprobante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado en"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("FA", "Factura A"),
                            ("FB", "Factura B"),
                            ("FC", "Factura C"),
                            ("NCA", "Nota de Crédito A"),
                            ("NCB", "Nota de Crédito B"),
                            ("NCC", "Nota de Crédito C"),
                        ],
                        max_length=5,
                        verbose_name="Tipo de comprobante",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente de envío a AFIP"),
                            ("emitido", "Emitido (CAE obtenido)"),
                            ("rechazado", "Rechazado por AFIP"),
                            ("anulado", "Anulado"),
                        ],
                        default="pendiente",
                        max_length=10,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "punto_venta",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Punto de venta"
                    ),
                ),
                (
                    "numero",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Número de comprobante"
                    ),
                ),
                (
                    "razon_social_receptor",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Razón social del receptor",
                    ),
                ),
                (
                    "cuit_receptor",
                    models.CharField(
                        blank=True, max_length=13, verbose_name="CUIT del receptor"
                    ),
                ),
                (
                    "condicion_iva_receptor",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="Condición IVA del receptor",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Subtotal neto",
                    ),
                ),
                (
                    "iva",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=14, verbose_name="IVA"
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=14, verbose_name="Total"
                    ),
                ),
                (
                    "cae",
                    models.CharField(blank=True, max_length=20, verbose_name="CAE"),
                ),
                (
                    "cae_vencimiento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Vencimiento del CAE"
                    ),
                ),
                (
                    "respuesta_afip",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Respuesta completa AFIP"
                    ),
                ),
                (
                    "comanda",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comprobante",
                        to="comandas.comanda",
                        verbose_name="Comanda",
                    ),
                ),
                (
                    "emitido_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comprobantes_emitidos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Emitido por",
                    ),
                ),
                (
                    "pedido",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comprobante",
                        to="pedidos.pedido",
                        verbose_name="Pedido online",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comprobante",
                "verbose_name_plural": "Comprobantes",
                "ordering": ["-creado_en"],
                "unique_together": {("tipo", "punto_venta", "numero")},
            },
        ),
        migrations.CreateModel(
            name="ItemComprobante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(max_length=200, verbose_name="Descripción"),
                ),
                (
                    "cantidad",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Cantidad"
                    ),
                ),
                (
                    "precio_unitario",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Precio unitario neto",
                    ),
                ),
                (
                    "alicuota_iva",
                    models.DecimalField(
                        decimal_places=2,
                        default=21,
                        max_digits=5,
                        verbose_name="Alícuota IVA (%)",
                    ),
                ),
                (
                    "comprobante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="facturacion.comprobante",
                        verbose_name="Comprobante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ítem de comprobante",
                "verbose_name_plural": "Ítems de comprobante",
            },
        ),
    ]
