# Generated by Django 4.2.29 on 2026-04-02 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facturacion", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comprobante",
            name="condicion_iva_receptor",
        ),
        migrations.RemoveField(
            model_name="comprobante",
            name="cuit_receptor",
        ),
        migrations.RemoveField(
            model_name="comprobante",
            name="respuesta_afip",
        ),
        migrations.AddField(
            model_name="comprobante",
            name="documento_receptor",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="RUT / CI del receptor"
            ),
        ),
        migrations.AddField(
            model_name="comprobante",
            name="respuesta_dgi",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Respuesta completa DGI"
            ),
        ),
        migrations.AddField(
            model_name="comprobante",
            name="tipo_documento_receptor",
            field=models.CharField(
                blank=True,
                max_length=50,
                verbose_name="Tipo de Documento (RUT/CI/Pasaporte)",
            ),
        ),
        migrations.AlterField(
            model_name="comprobante",
            name="estado",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente de envío a DGI"),
                    ("emitido", "Emitido (CAE obtenido)"),
                    ("rechazado", "Rechazado por DGI"),
                    ("anulado", "Anulado"),
                ],
                default="pendiente",
                max_length=10,
                verbose_name="Estado",
            ),
        ),
        migrations.AlterField(
            model_name="comprobante",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("101", "e-Ticket"),
                    ("102", "Nota de Crédito de e-Ticket"),
                    ("103", "Nota de Débito de e-Ticket"),
                    ("111", "e-Factura"),
                    ("112", "Nota de Crédito de e-Factura"),
                    ("113", "Nota de Débito de e-Factura"),
                ],
                max_length=5,
                verbose_name="Tipo de comprobante",
            ),
        ),
        migrations.AlterField(
            model_name="itemcomprobante",
            name="alicuota_iva",
            field=models.DecimalField(
                decimal_places=2,
                default=22,
                max_digits=5,
                verbose_name="Alícuota IVA (%)",
            ),
        ),
    ]
