# Generated by Django 4.2.29 on 2026-04-01 01:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado en"),
                ),
                ("nombre", models.CharField(max_length=80, verbose_name="Nombre")),
                ("apellido", models.CharField(max_length=80, verbose_name="Apellido")),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Teléfono"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "documento",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="DNI / Documento"
                    ),
                ),
                (
                    "direccion",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Dirección"
                    ),
                ),
                (
                    "fecha_nacimiento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de nacimiento"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                ("notas", models.TextField(blank=True, verbose_name="Notas internas")),
                (
                    "usuario",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="perfil_cliente",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario del sistema",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "ordering": ["apellido", "nombre"],
            },
        ),
    ]
