# Generated by Django 4.2.29 on 2026-03-31 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("catalogo", "0001_initial"),
        ("comandas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado en"),
                ),
                (
                    "numero",
                    models.PositiveIntegerField(
                        unique=True, verbose_name="Número de pedido"
                    ),
                ),
                (
                    "nombre_cliente",
                    models.CharField(max_length=120, verbose_name="Nombre del cliente"),
                ),
                (
                    "telefono_cliente",
                    models.CharField(max_length=30, verbose_name="Teléfono"),
                ),
                (
                    "email_cliente",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("take_away", "Take Away"), ("delivery", "Delivery")],
                        max_length=10,
                        verbose_name="Tipo de pedido",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("recibido", "Recibido"),
                            ("confirmado", "Confirmado"),
                            ("en_preparacion", "En preparación"),
                            ("listo", "Listo para retirar / Salió a entregar"),
                            ("en_camino", "En camino"),
                            ("entregado", "Entregado"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="recibido",
                        max_length=15,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "direccion_entrega",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Dirección de entrega"
                    ),
                ),
                (
                    "indicaciones_entrega",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Indicaciones de entrega",
                    ),
                ),
                (
                    "medio_pago",
                    models.CharField(
                        choices=[
                            ("efectivo", "Efectivo al recibir"),
                            ("mercado_pago", "Mercado Pago"),
                            ("transferencia", "Transferencia"),
                            ("qr", "QR"),
                        ],
                        max_length=15,
                        verbose_name="Medio de pago",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="Total"
                    ),
                ),
                ("pagado", models.BooleanField(default=False, verbose_name="Pagado")),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "atendido_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pedidos_atendidos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atendido por",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pedidos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cliente registrado",
                    ),
                ),
                (
                    "comanda_interna",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pedido_origen",
                        to="comandas.comanda",
                        verbose_name="Comanda interna",
                    ),
                ),
                (
                    "repartidor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pedidos_asignados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Repartidor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pedido online",
                "verbose_name_plural": "Pedidos online",
                "ordering": ["-creado_en"],
            },
        ),
        migrations.CreateModel(
            name="ItemPedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado en"),
                ),
                (
                    "cantidad",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Cantidad"
                    ),
                ),
                (
                    "precio_unitario",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Precio unitario"
                    ),
                ),
                ("observaciones", models.CharField(blank=True, max_length=200)),
                (
                    "combo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalogo.combo",
                        verbose_name="Combo",
                    ),
                ),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="pedidos.pedido",
                        verbose_name="Pedido",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalogo.producto",
                        verbose_name="Producto",
                    ),
                ),
                (
                    "variante",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalogo.varianteproducto",
                        verbose_name="Variante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ítem de pedido",
                "verbose_name_plural": "Ítems de pedido",
            },
        ),
    ]
