# Generated by Django 4.2.29 on 2026-03-31 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ubicacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado en"),
                ),
                ("nombre", models.CharField(max_length=80, verbose_name="Nombre")),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "orden",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Orden"),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
            ],
            options={
                "verbose_name": "Ubicación",
                "verbose_name_plural": "Ubicaciones",
                "ordering": ["orden", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="Mesa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado en"),
                ),
                (
                    "numero",
                    models.PositiveSmallIntegerField(verbose_name="Número de mesa"),
                ),
                (
                    "nombre",
                    models.CharField(
                        blank=True,
                        help_text="Ej: 'Terraza 1', 'Barra'. Opcional.",
                        max_length=40,
                        verbose_name="Nombre / alias",
                    ),
                ),
                (
                    "capacidad",
                    models.PositiveSmallIntegerField(
                        default=4, verbose_name="Capacidad (personas)"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("libre", "Libre"),
                            ("ocupada", "Ocupada"),
                            ("reservada", "Reservada"),
                            ("cerrada", "Cerrada"),
                        ],
                        default="libre",
                        max_length=10,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "pos_x",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Posición X"
                    ),
                ),
                (
                    "pos_y",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Posición Y"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "ubicacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mesas",
                        to="mesas.ubicacion",
                        verbose_name="Ubicación",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mesa",
                "verbose_name_plural": "Mesas",
                "ordering": ["ubicacion", "numero"],
                "unique_together": {("ubicacion", "numero")},
            },
        ),
    ]
