# Generated by Django 4.2.29 on 2026-03-31 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mesas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reserva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado en"),
                ),
                (
                    "nombre_contacto",
                    models.CharField(max_length=120, verbose_name="Nombre de contacto"),
                ),
                (
                    "telefono_contacto",
                    models.CharField(
                        max_length=30, verbose_name="Teléfono de contacto"
                    ),
                ),
                (
                    "email_contacto",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email de contacto"
                    ),
                ),
                ("fecha", models.DateField(verbose_name="Fecha")),
                ("hora", models.TimeField(verbose_name="Hora")),
                (
                    "cantidad_personas",
                    models.PositiveSmallIntegerField(
                        verbose_name="Cantidad de personas"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("confirmada", "Confirmada"),
                            ("cancelada", "Cancelada"),
                            ("completada", "Completada"),
                            ("no_show", "No se presentó"),
                        ],
                        default="pendiente",
                        max_length=12,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "origen",
                    models.CharField(
                        choices=[
                            ("web", "Formulario web"),
                            ("telefono", "Teléfono"),
                            ("interno", "Carga interna"),
                            ("whatsapp", "WhatsApp"),
                        ],
                        default="web",
                        max_length=10,
                        verbose_name="Origen",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "gestionada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservas_gestionadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Gestionada por",
                    ),
                ),
                (
                    "mesa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservas",
                        to="mesas.mesa",
                        verbose_name="Mesa asignada",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        help_text="Solo si el cliente tiene cuenta en el sistema.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario registrado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reserva",
                "verbose_name_plural": "Reservas",
                "ordering": ["fecha", "hora"],
            },
        ),
    ]
