# Generated by Django 4.2.29 on 2026-03-31 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Caja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado en"),
                ),
                ("abierta", models.BooleanField(default=True, verbose_name="Abierta")),
                (
                    "monto_inicial",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Monto inicial",
                    ),
                ),
                (
                    "monto_final_declarado",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Monto final declarado",
                    ),
                ),
                (
                    "observaciones_apertura",
                    models.TextField(
                        blank=True, verbose_name="Observaciones de apertura"
                    ),
                ),
                (
                    "cerrada_en",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Cerrada en"
                    ),
                ),
            ],
            options={
                "verbose_name": "Caja",
                "verbose_name_plural": "Cajas",
                "ordering": ["-creado_en"],
            },
        ),
        migrations.CreateModel(
            name="CierreCaja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "medio_pago",
                    models.CharField(
                        choices=[
                            ("efectivo", "Efectivo"),
                            ("debito", "Débito"),
                            ("credito", "Crédito"),
                            ("transferencia", "Transferencia"),
                            ("qr", "QR"),
                            ("mercado_pago", "Mercado Pago"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "total_cobrado",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_propinas",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
            ],
            options={
                "verbose_name": "Detalle de cierre de caja",
            },
        ),
        migrations.CreateModel(
            name="MovimientoCaja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado en"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("ingreso", "Ingreso"), ("egreso", "Egreso")],
                        max_length=8,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "medio_pago",
                    models.CharField(
                        choices=[
                            ("efectivo", "Efectivo"),
                            ("debito", "Débito"),
                            ("credito", "Crédito"),
                            ("transferencia", "Transferencia"),
                            ("qr", "QR"),
                            ("mercado_pago", "Mercado Pago"),
                        ],
                        default="efectivo",
                        max_length=15,
                        verbose_name="Medio de pago",
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Monto"
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Descripción"
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimiento de caja",
                "verbose_name_plural": "Movimientos de caja",
                "ordering": ["-creado_en"],
            },
        ),
        migrations.CreateModel(
            name="PagoComanda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado en"),
                ),
                (
                    "medio_pago",
                    models.CharField(
                        choices=[
                            ("efectivo", "Efectivo"),
                            ("debito", "Débito"),
                            ("credito", "Crédito"),
                            ("transferencia", "Transferencia"),
                            ("qr", "QR"),
                            ("mercado_pago", "Mercado Pago"),
                        ],
                        max_length=15,
                        verbose_name="Medio de pago",
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Monto"
                    ),
                ),
                (
                    "propina",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Propina",
                    ),
                ),
                (
                    "caja",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pagos",
                        to="cajas.caja",
                        verbose_name="Caja",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pago de comanda",
                "verbose_name_plural": "Pagos de comandas",
                "ordering": ["-creado_en"],
            },
        ),
    ]
