# Generated by Django 4.2.29 on 2026-03-31 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cajas", "0001_initial"),
        ("comandas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="pagocomanda",
            name="comanda",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pagos",
                to="comandas.comanda",
                verbose_name="Comanda",
            ),
        ),
        migrations.AddField(
            model_name="pagocomanda",
            name="registrado_por",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Registrado por",
            ),
        ),
        migrations.AddField(
            model_name="movimientocaja",
            name="caja",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movimientos",
                to="cajas.caja",
                verbose_name="Caja",
            ),
        ),
        migrations.AddField(
            model_name="movimientocaja",
            name="registrado_por",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Registrado por",
            ),
        ),
        migrations.AddField(
            model_name="cierrecaja",
            name="caja",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detalles_cierre",
                to="cajas.caja",
            ),
        ),
        migrations.AddField(
            model_name="caja",
            name="cajero",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cajas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Cajero",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cierrecaja",
            unique_together={("caja", "medio_pago")},
        ),
    ]
