# Generated by Django 4.2.29 on 2026-04-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cajas", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimientocaja",
            name="recibo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="cajas/recibos/",
                verbose_name="Recibo (imagen)",
            ),
        ),
    ]
